version: '3.7'

services:
  # React node container for developing the front end
  web-react:
    container_name: web-react
    build:
      context: ./web-react
      dockerfile: Dockerfile
    volumes:
      - './web-react:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # needed because react-scripts exits after running

  # Web server
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./cdn/:/usr/share/nginx/cdn
    depends_on:
      - web-react

  # C++ backend server for game stats
  stats-server:
    container_name: stats-server
    build:
      context: ./stats-server
      dockerfile: Dockerfile
