version: '3.7'

services:
  web-react:
    container_name: web-react
    build:
      context: ./web-react
      dockerfile: Dockerfile
    volumes:
      - './web-react:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # needed because react-scripts exits after running

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./cdn/:/usr/share/nginx/cdn