version: '3.7'

services:
  react-portfolio:
    container_name: react-portfolio
    build:
      context: ./react-portfolio
      dockerfile: Dockerfile
    volumes:
      - './react-portfolio:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # needed because react-scripts exits after running

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
