# pull official base image
FROM node:22.14.0-alpine as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH=/app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
RUN npm install react-scripts@5.0.1 -g

# add app
COPY . ./

# build production files
# This happens in docker-compose now
# RUN npm run build
